// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef AXI_BUS_ERR_UNIT_REG_H
#define AXI_BUS_ERR_UNIT_REG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - bus_err_unit::err_addr
#define BUS_ERR_UNIT__ERR_ADDR__ERR_ADDR_bm 0xffffffff
#define BUS_ERR_UNIT__ERR_ADDR__ERR_ADDR_bp 0
#define BUS_ERR_UNIT__ERR_ADDR__ERR_ADDR_bw 32
#define BUS_ERR_UNIT__ERR_ADDR__ERR_ADDR_reset 0x0

// Reg - bus_err_unit::err_addr_top
#define BUS_ERR_UNIT__ERR_ADDR_TOP__ERR_ADDR_TOP_bm 0xffffffff
#define BUS_ERR_UNIT__ERR_ADDR_TOP__ERR_ADDR_TOP_bp 0
#define BUS_ERR_UNIT__ERR_ADDR_TOP__ERR_ADDR_TOP_bw 32
#define BUS_ERR_UNIT__ERR_ADDR_TOP__ERR_ADDR_TOP_reset 0x0

// Reg - bus_err_unit::err_code
#define BUS_ERR_UNIT__ERR_CODE__ERR_CODE_bm 0xffffffff
#define BUS_ERR_UNIT__ERR_CODE__ERR_CODE_bp 0
#define BUS_ERR_UNIT__ERR_CODE__ERR_CODE_bw 32
#define BUS_ERR_UNIT__ERR_CODE__ERR_CODE_reset 0x0

// Reg - bus_err_unit::meta
#define BUS_ERR_UNIT__META__META_bm 0xffffffff
#define BUS_ERR_UNIT__META__META_bp 0
#define BUS_ERR_UNIT__META__META_bw 32
#define BUS_ERR_UNIT__META__META_reset 0x0

// Addrmap - bus_err_unit
typedef struct __attribute__ ((__packed__)) {
    uint32_t err_addr;
    uint32_t err_addr_top;
    uint32_t err_code;
    uint32_t meta;
} bus_err_unit_t;

// Addrmap - axi_bus_err_unit
typedef struct __attribute__ ((__packed__)) {
    bus_err_unit_t write_err_unit;
    uint8_t RESERVED_10_1f[0x10];
    bus_err_unit_t read_err_unit;
} axi_bus_err_unit_t;


static_assert(sizeof(axi_bus_err_unit_t) == 0x30, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* AXI_BUS_ERR_UNIT_REG_H */
