// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package bus_err_unit_reg_pkg;

    localparam BUS_ERR_UNIT_REG_TOP_DATA_WIDTH = 32;
    localparam BUS_ERR_UNIT_REG_TOP_MIN_ADDR_WIDTH = 4;
    localparam BUS_ERR_UNIT_REG_TOP_SIZE = 'h10;

    

    typedef struct packed {
        logic [31:0] err_addr;
    } bus_err_unit__err_addr__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        bus_err_unit__err_addr__external__fields__in_t rd_data;
    } bus_err_unit__err_addr__external__in_t;

    typedef struct packed {
        logic [31:0] err_addr_top;
    } bus_err_unit__err_addr_top__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        bus_err_unit__err_addr_top__external__fields__in_t rd_data;
    } bus_err_unit__err_addr_top__external__in_t;

    typedef struct packed {
        logic [31:0] err_code;
    } bus_err_unit__err_code__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        bus_err_unit__err_code__external__fields__in_t rd_data;
    } bus_err_unit__err_code__external__in_t;

    typedef struct packed {
        logic [31:0] meta;
    } bus_err_unit__meta__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        bus_err_unit__meta__external__fields__in_t rd_data;
    } bus_err_unit__meta__external__in_t;

    typedef struct {
        bus_err_unit__err_addr__external__in_t err_addr;
        bus_err_unit__err_addr_top__external__in_t err_addr_top;
        bus_err_unit__err_code__external__in_t err_code;
        bus_err_unit__meta__external__in_t meta;
    } bus_err_unit__in_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } bus_err_unit__err_addr__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } bus_err_unit__err_addr_top__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } bus_err_unit__err_code__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } bus_err_unit__meta__external__out_t;

    typedef struct {
        bus_err_unit__err_addr__external__out_t err_addr;
        bus_err_unit__err_addr_top__external__out_t err_addr_top;
        bus_err_unit__err_code__external__out_t err_code;
        bus_err_unit__meta__external__out_t meta;
    } bus_err_unit__out_t;
endpackage
